services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 20s
      timeout: 5s
      retries: 5
  
  back:
    build: ./back
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy